mdqinc/SDL_GameControllerDB

gamecontrollerdb.txt

Tested with the X360 OSX Driver [1] and SDL 2.0.3
1. http://tattiebogle.net/index.php/ProjectRoot/Xbox360Controller/OsxDriver

Add Gamestop BB-070 mappings for OSX

---

gamecontrollerdb.txt

Using wjoy as a Wiimote driver, on OSX 10.10.4

Add a Wiimote mapping

---

gamecontrollerdb.txt

Pulled from Steam's Big Picture config. It appears to be somewhat similar to the RetroUSB.com mappings.

Add iBuffalo classic usb gamepad mapping

---

gamecontrollerdb.txt

To clarify the changes I've made:
I've renamed it from "Wiimote" to "Wii Remote". This is what Nintendo officially calls it; "Wiimote" is just a nickname. Since the other controllers use their official names, it makes sense to change this one to it as well.
The other change I made was in the mapping. `b11` is the C button and `b12` is the Z button. Since the C button is above the Z button, it would make sense to have it mapped to RB. However, the mapping currently has the C button mapped to RT, which doesn't make a lot of sense. I switch the two around so that it's in the more natural order.

Improved Wii( Re)mode mapping for Mac OS X

---

gamecontrollerdb.txt

This one:
http://www.amazon.co.uk/Buffalo-Classic-USB-Gamepad-PC/dp/B002B9XB0E/ref=sr_1_fkmr0_1?ie=UTF8&qid=1447258451&sr=8-1-fkmr0&keywords=ibufalo+classic+usb+gamepad
The mappings and device name are identical to the linux bindings for this same gamepad.

Added support for the iBuffalo Classic USB Gamepad on osx

---

gamecontrollerdb.txt

These are mappings for XBox One controllers that appear through the [360Controller driver](https://github.com/360Controller/360Controller) on Mac OS X.
Tested with an Xbox One Covert Forces controller on OS X Yosemite with version 0.15 beta 5 of the 360Controller driver. I'm not sure what the firmware version on the controller is (I know that matters sometimes with XBox One controllers...) but I'm pretty sure the driver deals with that.

Added OS X mappings for Xbox One controllers

---

gamecontrollerdb.txt

I've added a few mappings for my personal game controllers.
For some odd reason the right bumper and both shoulders on the WiiU Pro controller do not work with either WJoy or the Mayflash adapter in Dinput mode in OS X (XInput mode works fine).

Added Mayflash adapters, WJoy (OS X) mappings

---

gamecontrollerdb.txt

Mac OS X, USB wired mode.
When in this mode it is reported to the system as: SFC Joystick
http://www.8bitdo.com/sfc30/

Added SFC30 Joystick

---

gamecontrollerdb.txt

Model number: ISS-5001
Manufacturer: SLS
Device name: USB Gamepad
Product ID:	0x010a
Vendor ID:	0x04b4  (Cypress Semiconductor)

Sega Saturn USB Gamepad

---

gamecontrollerdb.txt

It's a generic (but ergonomic) PlayStation DualShock clone.

Add support for the NGS Phantom USB gamepad in Windows

---

gamecontrollerdb.txt

This is a mapping for the Microntek USB Joystick. It actually uses axes for the directional pad, which is weird.

Add Microntek USB Joystick (Gamepad)

---

check.py

The code was being interpreted as `"+righty-leftx": ""`

check.py: fix initialization of Mapping.__keys

---

gamecontrollerdb.txt

Aside from the appearance, the 8Bitdo FC30 Pro is identical to the NES30, but it has a different name and GUID.

Add 8Bitdo FC30 Pro for Linux

---

README.md

We no longer strictly enforce map sorting or key sorting within maps.

Removed Steam Input map linting note in README

---

gamecontrollerdb.txt

These are USB adapters that allow you to connect old-school 9-pin controllers, from Amiga, Atari, SEGA etc. 
The mappings were tested on Linux using Amiberry (Amiga emulator for ARM).

Added OnyxSoft Dual JoyDivision and INNEX Genesis Controllers

---

gamecontrollerdb.txt

This adds Windows support for the official pads that ship with the Sega Genesis Mini.
Oddly, the d-pad is exposed as an analog input, though I've mapped it as a d-pad in this configuration. Other buttons are mapped as follows:
A -> Xbox A
B -> Xbox B
C -> Xbox X
Start -> Xbox Start
Generated using the SDL2 Gamepad Tool.

Add support for Sega Genesis Mini pads (Windows)

---

README.md

This is mostly just an excuse to shill. I made an open source equivalent of the SDL2 Gamepad Tool a while ago as a programming exercise. SDL2 Gamepad Tool has not been updated in years and some portions of that app don't quite work right. I figure it is better to have access to an open source app rather than having to rely on a proprietary app anyway.
SDL2 Gamepad Mapper:
https://gitlab.com/ryochan7/sdl2-gamepad-mapper
Latest release page:
https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases/v0.0.3

Added SDL2 Gamepad Mapper app to README

---

.github/workflows/check.yml
duplicates.py

sample output for #544
https://github.com/paroj/SDL_GameControllerDB/runs/4966298974?check_suite_focus=true
if you set CROSS_PLATFORM, it will help catching inconsistent naming, e.g.
```
Duplicate: 8Bitdo SFC30 GamePad Joystick at line 726
-8Bitdo SFC30 GamePad +8Bitdo SFC30 GamePad Joystick -platform:Windows +platform:Mac OS X
```

add github workflow to detect duplicates

---

README.md

I previously had trouble trying to find the official SDL tool. With this commit, I'm using the correct name for the tool, as well as providing a direct link to the tool in the SDL repository.

Fixed the SDL tool name, and added a link to its source code

---

gamecontrollerdb.txt

Add support for SNK Neo Geo Arcade Stick Pro on Mac OS X.
Product page: https://www.snk-corp.co.jp/us/neogeoarcadestickpro/

Add support for SNK Neo Geo Arcade Stick Pro on Mac OS X
